version: '3'

services:
  media-server:
    build:
      context: .
      dockerfile: apps/media-server/Dockerfile
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # HTTP (for HLS)
      - "3001:3001"  # API
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3001
      - STREAM_KEY_SECRET=your_secret_here
    volumes:
      - ./apps/media-server/hls:/opt/nginx/hls
    depends_on:
      - api

  api:
    image: node:18-alpine
    working_dir: /app
    command: npm run serve:media-server-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - STREAM_KEY_SECRET=your_secret_here
    volumes:
      - .:/app 